#!/usr/bin/env bash
# Author: NAZY-OS
# License: MIT
# Name: tty-dmesgd
# Version: 1.0.8
#
# This script repeatedly runs dmesg in follow mode and redirects its output
# to /dev/tty12. It requires root permissions. If not run as root, it exits.

set -euo pipefail

if [[ "${EUID}" -ne 0 ]]; then
  echo "Error: run as root." >&2
  exit 1
fi

## MAIN

echo "DMESG INFOS TO: /dev/tty12"
echo

while true; do
  sh -c "dmesg --human -T -l 6 -w --color --follow-new < /dev/tty12 > /dev/tty12 2>&1"
  sleep 1
done
